<?php

return [
    "employee" => [
        'table' => 'dbhrd.newdatakar',
        'default_alias' => 'nd',
        'primary_key'   => 'NIP',
        'columns' => [
            'NIP',
            'NAMA',
            'NODEP',
            'NM_DEPARTE',
            'NOBAG',
            'BAGIAN',
            'KDSEKSI',
            'NMSEKSI',
            'NOJAB',
            'NM_JABATAN',
            'LEVEL',
            'KETSEX',
            'TMP_LAHIR',
            'TGLLAHIR',
            'TGLMASUK',
            'KETKAWIN',
            'JM_ANAK',
            'JM_ANAK2',
            'ISTRI',
            'ANAK',
            'KPPH',
            'KDSTKERJA',
            'KETSTKERJA',
            'TAG',
            'KDGAJI',
            'KETSTGAJI',
            'KDGRPAB',
            'NMGRPAB',
            'KDDIDIK',
            'KETDIDIK',
            'NMSEKOLAH',
            'JURUSAN',
            'THLULUS',
            'KETAGAMA',
            'KDCAB',
            'NAMACAB',
            'TELP',
            'EMAIL',
            'ALM_ASAL',
            'ALAMAT',
            'NO_BPJS_KET',
            'NO_BPJS_KES',
            'KDBANK',
            'NMBANK',
            'NOREK',
            'PENGALAMAN',
            'KTP',
            'NPWP',
            'gbr',
            'STDATA',
            'VAKSIN',
            'Nilai',
            'TGLCREATE',
            'LASTUPDATE',
            'USERCREATE'
        ],
        'exists' => []
    ],
];
